# starship.toml

format = """
[\\[](bold)\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$env_var\
(:$sudo$status$jobs)\
[\\]](bold)$line_break\
$battery\
$character
"""

scan_timeout = 30
command_timeout = 500
add_newline = true

[battery]
format = "[$symbol]($style)"
full_symbol = ""
charging_symbol = ""
discharging_symbol = "!"
unknown_symbol = "!"
empty_symbol = "!"

[character]
format = "[\\$ ](bold #fd8924)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold #65D7FD"
read_only = " ro"
truncation_length = 30
truncate_to_repo = false

[git_branch]
format = "-[$symbol$branch]($style)"
symbol = ""

[git_commit]
tag_symbol = " tag "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[python]
format = '[\($virtualenv\)]($style)'
detect_extensions = []
detect_files = []

[status]
disabled = false
format = "[$int]($style)"

[jobs]
format = "[$symbol$number]($style)"
